title: Vishakh Pillai # your name (or website title) here
logo: "/images/linkedin_photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm Vish, a Data Scientist at Intel. My portfolio showcases the work I completed in my Masters in Information and Data Science (MIDS) program at UC Berkeley.
  <br><br>
  Based in New York City, I spend my free time tutoring underserved populations and improving my skills in jazz piano. One of my passions is carrying on my family's legacy of cooking South-Indian cuisine while adapting the recipes to my plant-based diet.
  <br><br>
  <a href="pdfs/resume04.pdf">View My Resume</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/vishakh-pillai/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/vishpillai123/ghg_forecasting">View My Recent Github Time-Series Project</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
